apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbHc3dTZqbC5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiZG5WellTNTBhR0Z1ZFhOb2EzVnRZWEpBZUdWeWIzZ3VZMjl0T2xSb1lXNTFjMmhBTnpnME1nPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
